# frozen_string_literal: true

# Feed Monitor engine configuration for the dummy host app.
# This file is generated by the install generator and tweaked here so the
# integration playground uses all background-processing features.
FeedMonitor.configure do |config|
  # Keep the default namespace so queue names remain stable across environments.
  config.queue_namespace = "feed_monitor"

  # Ensure queues align with Solid Queue workers launched via bin/dev.
  config.fetch_queue_name = "#{config.queue_namespace}_fetch"
  config.scrape_queue_name = "#{config.queue_namespace}_scrape"
  config.fetch_queue_concurrency = 2
  config.scrape_queue_concurrency = 2

  # The dashboard should surface queue metrics in development.
  config.job_metrics_enabled = true

  # Mission Control is mounted in the dummy app; surface the link by default.
  config.mission_control_enabled = true
  config.mission_control_dashboard_path = -> { "/mission_control" }
end
